version: "3"

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: souko
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c " ./manage.py migrate --noinput && ./manage.py runserver_plus --print-sql 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    links:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: bash -c "./manage.py run-worker"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db

  celery-beat:
    build: .
    command: bash -c "celery -A soukoapi beat -l info --scheduler main.scheduler.SmartScheduler --pidfile="
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db
volumes:
  postgres_data:
