---

# Virtualenv settings.
enable_deadsnakes_ppa: true
recreate_virtualenv: false
virtualenv_python_version: "{{ base_python_package }}"


# Application settings.
virtualenv_path: "/opt/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements.txt"


# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: souko


# Nginx settings.
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ project_path }}/static/"
nginx_media_dir: "{{ virtualenv_path }}/media/"


# Django environment variables.
django_environment:
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  DATABASE_PORT: 5432
  DATABASE_HOST: "localhost"
  REDIS_URL: "{{ redis_url }}"
  SENDGRID_API_KEY: "{{ sendgrid_api_key }}"
  TEMPLATE_EMAIL_WITH_URL_ID: "{{ template_email_with_url_id }}"
  TEMPLATE_EMAIL_WITH_MESSAGE_ID: "{{ template_email_with_message_id }}"
  FRONTEND_BASE_URL: "{{ frontend_base_url }}"
  EMAIL_BASE_URL: "{{ email_base_url }}"
  SENDER_EMAIL: "{{ sender_email }}"
  SENTRY_DSN: "{{ sentry_dsn }}"
  AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
  AWS_STORAGE_BUCKET_NAME: "{{ aws_storage_bucket_name }}"
  AWS_DEFAULT_ACL: "{{ aws_default_acl }}"
  AWS_S3_REGION_NAME: "{{ aws_s3_region_name }}"
  AWS_S3_CUSTOM_DOMAIN: "{{ aws_s3_custom_domain }}"
  AWS_S3_COMPRESSED_IMAGES_DOMAIN: "{{ aws_s3_compressed_images_domain }}"
