# Generated by Django 2.2.5 on 2020-12-14 16:45

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=django_countries.fields.CountryField(default='GH', max_length=2),
        ),
        migrations.AlterField(
            model_name='admin',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='main.Store'),
        ),
    ]
