# Generated by Django 2.2.5 on 2020-12-15 00:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201214_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Customer Id')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Last Name')),
                ('dob', models.DateTimeField(blank=True, null=True, verbose_name='Date of birth')),
                ('city', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='City')),
                ('country', django_countries.fields.CountryField(default='GH', max_length=2)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Address')),
                ('other_address_details', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Other Address Details')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='main.Store')),
            ],
            options={
                'verbose_name_plural': 'customers',
                'ordering': ('id',),
            },
        ),
    ]
