# Generated by Django 2.2.5 on 2020-12-16 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Product Id')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True)),
                ('buying_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Buying / Production Price')),
                ('selling_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Selling Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Store')),
            ],
            options={
                'verbose_name_plural': 'products',
                'ordering': ('id',),
            },
        ),
    ]
