# Generated by Django 2.2.5 on 2020-12-16 21:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Order Id')),
                ('delivery_fee', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Today Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'orders',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'admins'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('name',), 'verbose_name_plural': 'stores'},
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Order Item Id')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='main.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='main.Product')),
            ],
            options={
                'verbose_name_plural': 'order_items',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.Store'),
        ),
    ]
