# Generated by Django 2.2.5 on 2020-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=255, null=True, verbose_name='Role'),
        ),
    ]
