# Generated by Django 2.2.5 on 2020-12-23 19:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersTimestampedMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Order Metrics Id')),
                ('orders', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_metrics', to='main.Store')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
