# Generated by Django 2.2.5 on 2021-02-02 11:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210202_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProfitTimestampedMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Profit Metrics Id')),
                ('profit', models.FloatField(blank=True, default=0.0, null=True)),
                ('date', models.DateField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_metrics', to='main.Store')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
