# Generated by Django 2.2.5 on 2021-02-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210202_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='currency',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='Currency'),
        ),
    ]
