# Generated by Django 2.2.5 on 2021-02-28 12:59

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_store_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_picture_url',
            field=main.models.UniqueNameFileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_url',
            field=main.models.UniqueNameFileField(blank=True, null=True, upload_to=''),
        ),
    ]
