# Generated by Django 2.2.5 on 2021-04-06 18:24

from django.db import migrations, models
import main.generators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210314_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default=main.generators.generate_order_number, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Not Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='PENDING', max_length=255, null=True, verbose_name='Role'),
        ),
    ]
