# Generated by Django 2.2.5 on 2021-04-26 21:16

from django.db import migrations

def create_free_plan(apps, schema_editor):
    SubscriptionPlan = apps.get_model('main', 'SubscriptionPlan')
    SubscriptionPlan.objects.create( **{
        'products_limit': 35,
        'orders_limit': -1,
        'customers_limit': -1
    } )

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_storesubscription_subscriptionplan'),
    ]

    operations = [
        migrations.RunPython(create_free_plan),
    ]
