# Generated by Django 2.2.5 on 2021-05-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=True, verbose_name='Is deleted'),
        ),
    ]
