# Generated by Django 2.2.5 on 2021-07-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210515_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category name in english'),
        ),
        migrations.AddField(
            model_name='category',
            name='fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category name in french'),
        ),
    ]
