---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  become: true
  become_user: root
  remote_user: root
  vars:
    update_apt_cache: true
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml
    - secrets.yml

  roles:
    - base
    - avahi
    - redis
    - db
    - web
    - celery
    - certbot
    - nginx
