---

- name: Download certbot
  get_url: url=https://gist.githubusercontent.com/akornor/23ba48a628f57fd4a8f7f63badd1ba76/raw/de9787a06110c13a79f4ebf4237abf13fd342e2b/certbot-auto dest={{ certbot_script }} mode=0755

- name: Check if Nginx exists
  stat: path=/etc/init.d/nginx
  register: nginx_status

- name: Ensure Nginx is stopped
  service: name=nginx state=stopped
  when: nginx_status.stat.exists

- name: Install certbot and generate cert
  command: "{{ certbot_script }} certonly --noninteractive --agree-tos --standalone --email {{ certbot_admin_email }} -d {{ inventory_hostname }}"
  args:
    creates: "{{ certbot_output_dir }}"

- name: Ensure Nginx is started
  service: name=nginx state=started
  when: nginx_status.stat.exists

- name: Ensure a cron job to auto-renew the cert exists
  cron: name="daily auto renew cert"
        special_time=daily
        job="{{ certbot_script }} renew --standalone --no-self-upgrade --pre-hook \"service nginx stop\" --post-hook \"service nginx start\" --quiet"
        state=present
  when: certbot_auto_renew
